name: Build and Deploy

on:
  push:
    branches: [ master, pipelines ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./codebase

    strategy:
      matrix:
        node-version: [12.x]

    steps:
    - uses: actions/checkout@v2
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node-version }}
    - name: Install yarn package manager
      run: npm install -g yarn 
    - name: Install project dependencies
      run: yarn install
    - name: Build the application
      run: yarn build
    - name: List files
      run: ls
      
