name: Build and Deploy

on:
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./codebase

    strategy:
      matrix:
        node-version: [12.x]

    steps:
    - uses: actions/checkout@v2
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node-version }}
    - name: Install yarn package manager
      run: npm install -g yarn 
    - name: Install project dependencies
      run: yarn install
    - name: Build the application
      run: yarn build
    - name: SFTP Deploy
      uses: wlixcc/SFTP-Deploy-Action@v1.0
      with:
        username: ${{ secrets.SFTP_USER }} 
        server: ${{ secrets.SFTP_SERVER }} 
        port: 22
        ssh_private_key: ${{ secrets.SFTP_KEY }} 
        local_path: ./codebase/dist/*
        remote_path: /var/www/jordanchappell.com/source/jordantris
      
