name: Build and Test

on:
  pull_request:
    branches: 
    - master
  workflow_dispatch:

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./codebase

    steps:
    - uses: actions/checkout@v2
    - name: Use Node.js 12.x
      uses: actions/setup-node@v1
      with:
        node-version: 12.x
    - name: Install yarn package manager
      run: npm install -g yarn 
    - name: Install project dependencies
      run: yarn install
    - name: Build the application
      run: yarn build
    - name: Upload a build artifact
      uses: actions/upload-artifact@v2.1.4
      with:
        name: drop
        path: ./*
      
  test:
    name: Test
    runs-on: ubuntu-latest
    steps:
      - name: Use Node.js 12.x
        uses: actions/setup-node@v1
        with:
          node-version: 12.x
      - name: Install yarn package manager
        run: npm install -g yarn 
      - name: Download build artifacts
        uses: actions/download-artifact@v2.0.5
        with:
          name: drop
      - name: List files
        run: ls
      - name: Test the application
        run: yarn test
    
      
